name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-16"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMWY4NjAxYzMtZDQyMi00NDAyLWExOGQtOTE4ODAxZDEzMzY5IiwidGVuYW50X2lkIjoiOTUzNTIyZTFjNDYwOTkzMmRiYTA1ZTU3YjA2NmY3OGVkOWI1ZTYxY2E5ZTU1NGQzNGIwMmZkNjViNTYwOTRiNSIsImludGVybmFsX3NlY3JldCI6IjJmNzMxMmIxLWU5NzAtNGQ0OC1iY2E4LWRlYTIyZjM3NjQ5YiJ9.TLkumYN_dTbyQu3w9lRLkpPCE3fseq_02DvaKOl8gjc"
JWT_SECRET = "pro_jwt_secret"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



